services:
  app:
    image: serversideup/php:8.4-fpm-nginx-alpine
    container_name: laravel-app
    environment:
      # mixed for (Both http/https) Better to use full for production
      SSL_MODE: "off"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./blog-app:/var/www/html
